// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v3.12.4
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "user";

export interface ToggleUserProfileCheckRequset {
  toggle: boolean;
}

export interface ToggleUserProfileCheckResponse {
  success: boolean;
}

export interface GetUserProfileRequest {
  userId: number;
  whoFind: number;
}

export interface UpdateUserProfileRequest {
  userId: number;
  description: string;
}

export interface UpdateUserPasswordRequest {
  userId: number;
  password: string;
}

export interface GetUserProfileResponse {
  message: string;
  status: number;
}

export interface UpdateUserProfileResponse {
  message: string;
  status: number;
}

export interface UpdateUserPasswordResponse {
  message: string;
  status: number;
}

export interface GetPasswordUserRequest {
  userId: number;
}

export interface GetPasswordUserResponse {
  hashedPassword: string;
}

export interface RemoveAccountRequest {
  userId: number;
}

export interface RemoveAccountResponse {
  message: string;
}

export interface RemoveArrayChatRequest {
  chatId: string;
  data: ArrayLinkUsers[];
}

export interface ArrayLinkUsers {
  userId: number;
}

export interface RemoveArrayChatResponse {
  message: string;
  status: number;
}

export interface AddChatToUserRequest {
  userId: number;
  chatId: string;
}

export interface AddChatToUserResponse {
  info: ResponseMessage | undefined;
}

export interface RemoveChatFromUserRequest {
  userId: number;
  chatId: string;
}

export interface RemoveChatFromUserResponse {
  info: ResponseMessage | undefined;
}

export interface CreateNewUserRequest {
  email: string;
  passwordHash: string;
  phoneNumber: string;
  username: string;
}

export interface CreateNewUserResponse {
  info: ResponseMessage | undefined;
}

export interface FindUserByIdRequest {
  userId: number;
}

export interface FindUserByIdResponse {
  userData?: UserDataId | undefined;
  notFound?: UserNotFoundResponse | undefined;
}

export interface UserDataId {
  userId: number;
  phoneNumber: string;
  email: string;
  passwordHash: string;
  username: string;
  chatReferences: string[];
}

export interface FindUserByUsernameRequest {
  username: string;
}

export interface FindUserByUsernameResponse {
  users: UserArray[];
}

export interface FindUserByEmailRequest {
  email: string;
}

export interface FindUserByEmailResponse {
  userData?: UserData | undefined;
  notFound?: UserNotFoundResponse | undefined;
}

export interface FindUserByPhoneNumberRequest {
  phoneNumber: string;
}

export interface FindUserByPhoneNumberResponse {
  userData?: UserData | undefined;
  notFound?: UserNotFoundResponse | undefined;
}

export interface UserData {
  userId: number;
  phoneNumber: string;
  email: string;
  passwordHash: string;
  username: string;
}

export interface UserNotFoundResponse {
  message: string;
  status: number;
}

export interface ResponseMessage {
  message: string;
  status: number;
}

export interface UserArray {
  userId: number;
  username: string;
}

function createBaseToggleUserProfileCheckRequset(): ToggleUserProfileCheckRequset {
  return { toggle: false };
}

export const ToggleUserProfileCheckRequset: MessageFns<ToggleUserProfileCheckRequset> = {
  encode(message: ToggleUserProfileCheckRequset, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.toggle !== false) {
      writer.uint32(8).bool(message.toggle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToggleUserProfileCheckRequset {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToggleUserProfileCheckRequset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.toggle = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToggleUserProfileCheckRequset {
    return { toggle: isSet(object.toggle) ? globalThis.Boolean(object.toggle) : false };
  },

  toJSON(message: ToggleUserProfileCheckRequset): unknown {
    const obj: any = {};
    if (message.toggle !== false) {
      obj.toggle = message.toggle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToggleUserProfileCheckRequset>, I>>(base?: I): ToggleUserProfileCheckRequset {
    return ToggleUserProfileCheckRequset.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToggleUserProfileCheckRequset>, I>>(
    object: I,
  ): ToggleUserProfileCheckRequset {
    const message = createBaseToggleUserProfileCheckRequset();
    message.toggle = object.toggle ?? false;
    return message;
  },
};

function createBaseToggleUserProfileCheckResponse(): ToggleUserProfileCheckResponse {
  return { success: false };
}

export const ToggleUserProfileCheckResponse: MessageFns<ToggleUserProfileCheckResponse> = {
  encode(message: ToggleUserProfileCheckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToggleUserProfileCheckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToggleUserProfileCheckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToggleUserProfileCheckResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: ToggleUserProfileCheckResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToggleUserProfileCheckResponse>, I>>(base?: I): ToggleUserProfileCheckResponse {
    return ToggleUserProfileCheckResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToggleUserProfileCheckResponse>, I>>(
    object: I,
  ): ToggleUserProfileCheckResponse {
    const message = createBaseToggleUserProfileCheckResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseGetUserProfileRequest(): GetUserProfileRequest {
  return { userId: 0, whoFind: 0 };
}

export const GetUserProfileRequest: MessageFns<GetUserProfileRequest> = {
  encode(message: GetUserProfileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.whoFind !== 0) {
      writer.uint32(16).int32(message.whoFind);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.whoFind = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserProfileRequest {
    return {
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      whoFind: isSet(object.whoFind) ? globalThis.Number(object.whoFind) : 0,
    };
  },

  toJSON(message: GetUserProfileRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.whoFind !== 0) {
      obj.whoFind = Math.round(message.whoFind);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserProfileRequest>, I>>(base?: I): GetUserProfileRequest {
    return GetUserProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserProfileRequest>, I>>(object: I): GetUserProfileRequest {
    const message = createBaseGetUserProfileRequest();
    message.userId = object.userId ?? 0;
    message.whoFind = object.whoFind ?? 0;
    return message;
  },
};

function createBaseUpdateUserProfileRequest(): UpdateUserProfileRequest {
  return { userId: 0, description: "" };
}

export const UpdateUserProfileRequest: MessageFns<UpdateUserProfileRequest> = {
  encode(message: UpdateUserProfileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserProfileRequest {
    return {
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: UpdateUserProfileRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUserProfileRequest>, I>>(base?: I): UpdateUserProfileRequest {
    return UpdateUserProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUserProfileRequest>, I>>(object: I): UpdateUserProfileRequest {
    const message = createBaseUpdateUserProfileRequest();
    message.userId = object.userId ?? 0;
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseUpdateUserPasswordRequest(): UpdateUserPasswordRequest {
  return { userId: 0, password: "" };
}

export const UpdateUserPasswordRequest: MessageFns<UpdateUserPasswordRequest> = {
  encode(message: UpdateUserPasswordRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserPasswordRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserPasswordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserPasswordRequest {
    return {
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: UpdateUserPasswordRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUserPasswordRequest>, I>>(base?: I): UpdateUserPasswordRequest {
    return UpdateUserPasswordRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUserPasswordRequest>, I>>(object: I): UpdateUserPasswordRequest {
    const message = createBaseUpdateUserPasswordRequest();
    message.userId = object.userId ?? 0;
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseGetUserProfileResponse(): GetUserProfileResponse {
  return { message: "", status: 0 };
}

export const GetUserProfileResponse: MessageFns<GetUserProfileResponse> = {
  encode(message: GetUserProfileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserProfileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserProfileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserProfileResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
    };
  },

  toJSON(message: GetUserProfileResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserProfileResponse>, I>>(base?: I): GetUserProfileResponse {
    return GetUserProfileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserProfileResponse>, I>>(object: I): GetUserProfileResponse {
    const message = createBaseGetUserProfileResponse();
    message.message = object.message ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseUpdateUserProfileResponse(): UpdateUserProfileResponse {
  return { message: "", status: 0 };
}

export const UpdateUserProfileResponse: MessageFns<UpdateUserProfileResponse> = {
  encode(message: UpdateUserProfileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserProfileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserProfileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserProfileResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
    };
  },

  toJSON(message: UpdateUserProfileResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUserProfileResponse>, I>>(base?: I): UpdateUserProfileResponse {
    return UpdateUserProfileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUserProfileResponse>, I>>(object: I): UpdateUserProfileResponse {
    const message = createBaseUpdateUserProfileResponse();
    message.message = object.message ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseUpdateUserPasswordResponse(): UpdateUserPasswordResponse {
  return { message: "", status: 0 };
}

export const UpdateUserPasswordResponse: MessageFns<UpdateUserPasswordResponse> = {
  encode(message: UpdateUserPasswordResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserPasswordResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserPasswordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserPasswordResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
    };
  },

  toJSON(message: UpdateUserPasswordResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUserPasswordResponse>, I>>(base?: I): UpdateUserPasswordResponse {
    return UpdateUserPasswordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUserPasswordResponse>, I>>(object: I): UpdateUserPasswordResponse {
    const message = createBaseUpdateUserPasswordResponse();
    message.message = object.message ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseGetPasswordUserRequest(): GetPasswordUserRequest {
  return { userId: 0 };
}

export const GetPasswordUserRequest: MessageFns<GetPasswordUserRequest> = {
  encode(message: GetPasswordUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPasswordUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPasswordUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPasswordUserRequest {
    return { userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0 };
  },

  toJSON(message: GetPasswordUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPasswordUserRequest>, I>>(base?: I): GetPasswordUserRequest {
    return GetPasswordUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPasswordUserRequest>, I>>(object: I): GetPasswordUserRequest {
    const message = createBaseGetPasswordUserRequest();
    message.userId = object.userId ?? 0;
    return message;
  },
};

function createBaseGetPasswordUserResponse(): GetPasswordUserResponse {
  return { hashedPassword: "" };
}

export const GetPasswordUserResponse: MessageFns<GetPasswordUserResponse> = {
  encode(message: GetPasswordUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hashedPassword !== "") {
      writer.uint32(10).string(message.hashedPassword);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPasswordUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPasswordUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hashedPassword = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPasswordUserResponse {
    return { hashedPassword: isSet(object.hashedPassword) ? globalThis.String(object.hashedPassword) : "" };
  },

  toJSON(message: GetPasswordUserResponse): unknown {
    const obj: any = {};
    if (message.hashedPassword !== "") {
      obj.hashedPassword = message.hashedPassword;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPasswordUserResponse>, I>>(base?: I): GetPasswordUserResponse {
    return GetPasswordUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPasswordUserResponse>, I>>(object: I): GetPasswordUserResponse {
    const message = createBaseGetPasswordUserResponse();
    message.hashedPassword = object.hashedPassword ?? "";
    return message;
  },
};

function createBaseRemoveAccountRequest(): RemoveAccountRequest {
  return { userId: 0 };
}

export const RemoveAccountRequest: MessageFns<RemoveAccountRequest> = {
  encode(message: RemoveAccountRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveAccountRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveAccountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveAccountRequest {
    return { userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0 };
  },

  toJSON(message: RemoveAccountRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveAccountRequest>, I>>(base?: I): RemoveAccountRequest {
    return RemoveAccountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveAccountRequest>, I>>(object: I): RemoveAccountRequest {
    const message = createBaseRemoveAccountRequest();
    message.userId = object.userId ?? 0;
    return message;
  },
};

function createBaseRemoveAccountResponse(): RemoveAccountResponse {
  return { message: "" };
}

export const RemoveAccountResponse: MessageFns<RemoveAccountResponse> = {
  encode(message: RemoveAccountResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveAccountResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveAccountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveAccountResponse {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: RemoveAccountResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveAccountResponse>, I>>(base?: I): RemoveAccountResponse {
    return RemoveAccountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveAccountResponse>, I>>(object: I): RemoveAccountResponse {
    const message = createBaseRemoveAccountResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseRemoveArrayChatRequest(): RemoveArrayChatRequest {
  return { chatId: "", data: [] };
}

export const RemoveArrayChatRequest: MessageFns<RemoveArrayChatRequest> = {
  encode(message: RemoveArrayChatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chatId !== "") {
      writer.uint32(10).string(message.chatId);
    }
    for (const v of message.data) {
      ArrayLinkUsers.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveArrayChatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveArrayChatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data.push(ArrayLinkUsers.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveArrayChatRequest {
    return {
      chatId: isSet(object.chatId) ? globalThis.String(object.chatId) : "",
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => ArrayLinkUsers.fromJSON(e)) : [],
    };
  },

  toJSON(message: RemoveArrayChatRequest): unknown {
    const obj: any = {};
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    if (message.data?.length) {
      obj.data = message.data.map((e) => ArrayLinkUsers.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveArrayChatRequest>, I>>(base?: I): RemoveArrayChatRequest {
    return RemoveArrayChatRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveArrayChatRequest>, I>>(object: I): RemoveArrayChatRequest {
    const message = createBaseRemoveArrayChatRequest();
    message.chatId = object.chatId ?? "";
    message.data = object.data?.map((e) => ArrayLinkUsers.fromPartial(e)) || [];
    return message;
  },
};

function createBaseArrayLinkUsers(): ArrayLinkUsers {
  return { userId: 0 };
}

export const ArrayLinkUsers: MessageFns<ArrayLinkUsers> = {
  encode(message: ArrayLinkUsers, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArrayLinkUsers {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArrayLinkUsers();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArrayLinkUsers {
    return { userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0 };
  },

  toJSON(message: ArrayLinkUsers): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArrayLinkUsers>, I>>(base?: I): ArrayLinkUsers {
    return ArrayLinkUsers.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArrayLinkUsers>, I>>(object: I): ArrayLinkUsers {
    const message = createBaseArrayLinkUsers();
    message.userId = object.userId ?? 0;
    return message;
  },
};

function createBaseRemoveArrayChatResponse(): RemoveArrayChatResponse {
  return { message: "", status: 0 };
}

export const RemoveArrayChatResponse: MessageFns<RemoveArrayChatResponse> = {
  encode(message: RemoveArrayChatResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveArrayChatResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveArrayChatResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveArrayChatResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
    };
  },

  toJSON(message: RemoveArrayChatResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveArrayChatResponse>, I>>(base?: I): RemoveArrayChatResponse {
    return RemoveArrayChatResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveArrayChatResponse>, I>>(object: I): RemoveArrayChatResponse {
    const message = createBaseRemoveArrayChatResponse();
    message.message = object.message ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseAddChatToUserRequest(): AddChatToUserRequest {
  return { userId: 0, chatId: "" };
}

export const AddChatToUserRequest: MessageFns<AddChatToUserRequest> = {
  encode(message: AddChatToUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.chatId !== "") {
      writer.uint32(18).string(message.chatId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddChatToUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddChatToUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddChatToUserRequest {
    return {
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      chatId: isSet(object.chatId) ? globalThis.String(object.chatId) : "",
    };
  },

  toJSON(message: AddChatToUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddChatToUserRequest>, I>>(base?: I): AddChatToUserRequest {
    return AddChatToUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddChatToUserRequest>, I>>(object: I): AddChatToUserRequest {
    const message = createBaseAddChatToUserRequest();
    message.userId = object.userId ?? 0;
    message.chatId = object.chatId ?? "";
    return message;
  },
};

function createBaseAddChatToUserResponse(): AddChatToUserResponse {
  return { info: undefined };
}

export const AddChatToUserResponse: MessageFns<AddChatToUserResponse> = {
  encode(message: AddChatToUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.info !== undefined) {
      ResponseMessage.encode(message.info, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddChatToUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddChatToUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.info = ResponseMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddChatToUserResponse {
    return { info: isSet(object.info) ? ResponseMessage.fromJSON(object.info) : undefined };
  },

  toJSON(message: AddChatToUserResponse): unknown {
    const obj: any = {};
    if (message.info !== undefined) {
      obj.info = ResponseMessage.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddChatToUserResponse>, I>>(base?: I): AddChatToUserResponse {
    return AddChatToUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddChatToUserResponse>, I>>(object: I): AddChatToUserResponse {
    const message = createBaseAddChatToUserResponse();
    message.info = (object.info !== undefined && object.info !== null)
      ? ResponseMessage.fromPartial(object.info)
      : undefined;
    return message;
  },
};

function createBaseRemoveChatFromUserRequest(): RemoveChatFromUserRequest {
  return { userId: 0, chatId: "" };
}

export const RemoveChatFromUserRequest: MessageFns<RemoveChatFromUserRequest> = {
  encode(message: RemoveChatFromUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.chatId !== "") {
      writer.uint32(18).string(message.chatId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveChatFromUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveChatFromUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveChatFromUserRequest {
    return {
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      chatId: isSet(object.chatId) ? globalThis.String(object.chatId) : "",
    };
  },

  toJSON(message: RemoveChatFromUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveChatFromUserRequest>, I>>(base?: I): RemoveChatFromUserRequest {
    return RemoveChatFromUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveChatFromUserRequest>, I>>(object: I): RemoveChatFromUserRequest {
    const message = createBaseRemoveChatFromUserRequest();
    message.userId = object.userId ?? 0;
    message.chatId = object.chatId ?? "";
    return message;
  },
};

function createBaseRemoveChatFromUserResponse(): RemoveChatFromUserResponse {
  return { info: undefined };
}

export const RemoveChatFromUserResponse: MessageFns<RemoveChatFromUserResponse> = {
  encode(message: RemoveChatFromUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.info !== undefined) {
      ResponseMessage.encode(message.info, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveChatFromUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveChatFromUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.info = ResponseMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveChatFromUserResponse {
    return { info: isSet(object.info) ? ResponseMessage.fromJSON(object.info) : undefined };
  },

  toJSON(message: RemoveChatFromUserResponse): unknown {
    const obj: any = {};
    if (message.info !== undefined) {
      obj.info = ResponseMessage.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveChatFromUserResponse>, I>>(base?: I): RemoveChatFromUserResponse {
    return RemoveChatFromUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveChatFromUserResponse>, I>>(object: I): RemoveChatFromUserResponse {
    const message = createBaseRemoveChatFromUserResponse();
    message.info = (object.info !== undefined && object.info !== null)
      ? ResponseMessage.fromPartial(object.info)
      : undefined;
    return message;
  },
};

function createBaseCreateNewUserRequest(): CreateNewUserRequest {
  return { email: "", passwordHash: "", phoneNumber: "", username: "" };
}

export const CreateNewUserRequest: MessageFns<CreateNewUserRequest> = {
  encode(message: CreateNewUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.passwordHash !== "") {
      writer.uint32(18).string(message.passwordHash);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(26).string(message.phoneNumber);
    }
    if (message.username !== "") {
      writer.uint32(34).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateNewUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateNewUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.passwordHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateNewUserRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      passwordHash: isSet(object.passwordHash) ? globalThis.String(object.passwordHash) : "",
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
    };
  },

  toJSON(message: CreateNewUserRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.passwordHash !== "") {
      obj.passwordHash = message.passwordHash;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateNewUserRequest>, I>>(base?: I): CreateNewUserRequest {
    return CreateNewUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateNewUserRequest>, I>>(object: I): CreateNewUserRequest {
    const message = createBaseCreateNewUserRequest();
    message.email = object.email ?? "";
    message.passwordHash = object.passwordHash ?? "";
    message.phoneNumber = object.phoneNumber ?? "";
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseCreateNewUserResponse(): CreateNewUserResponse {
  return { info: undefined };
}

export const CreateNewUserResponse: MessageFns<CreateNewUserResponse> = {
  encode(message: CreateNewUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.info !== undefined) {
      ResponseMessage.encode(message.info, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateNewUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateNewUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.info = ResponseMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateNewUserResponse {
    return { info: isSet(object.info) ? ResponseMessage.fromJSON(object.info) : undefined };
  },

  toJSON(message: CreateNewUserResponse): unknown {
    const obj: any = {};
    if (message.info !== undefined) {
      obj.info = ResponseMessage.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateNewUserResponse>, I>>(base?: I): CreateNewUserResponse {
    return CreateNewUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateNewUserResponse>, I>>(object: I): CreateNewUserResponse {
    const message = createBaseCreateNewUserResponse();
    message.info = (object.info !== undefined && object.info !== null)
      ? ResponseMessage.fromPartial(object.info)
      : undefined;
    return message;
  },
};

function createBaseFindUserByIdRequest(): FindUserByIdRequest {
  return { userId: 0 };
}

export const FindUserByIdRequest: MessageFns<FindUserByIdRequest> = {
  encode(message: FindUserByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindUserByIdRequest {
    return { userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0 };
  },

  toJSON(message: FindUserByIdRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindUserByIdRequest>, I>>(base?: I): FindUserByIdRequest {
    return FindUserByIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindUserByIdRequest>, I>>(object: I): FindUserByIdRequest {
    const message = createBaseFindUserByIdRequest();
    message.userId = object.userId ?? 0;
    return message;
  },
};

function createBaseFindUserByIdResponse(): FindUserByIdResponse {
  return { userData: undefined, notFound: undefined };
}

export const FindUserByIdResponse: MessageFns<FindUserByIdResponse> = {
  encode(message: FindUserByIdResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userData !== undefined) {
      UserDataId.encode(message.userData, writer.uint32(10).fork()).join();
    }
    if (message.notFound !== undefined) {
      UserNotFoundResponse.encode(message.notFound, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByIdResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByIdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userData = UserDataId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.notFound = UserNotFoundResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindUserByIdResponse {
    return {
      userData: isSet(object.userData) ? UserDataId.fromJSON(object.userData) : undefined,
      notFound: isSet(object.notFound) ? UserNotFoundResponse.fromJSON(object.notFound) : undefined,
    };
  },

  toJSON(message: FindUserByIdResponse): unknown {
    const obj: any = {};
    if (message.userData !== undefined) {
      obj.userData = UserDataId.toJSON(message.userData);
    }
    if (message.notFound !== undefined) {
      obj.notFound = UserNotFoundResponse.toJSON(message.notFound);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindUserByIdResponse>, I>>(base?: I): FindUserByIdResponse {
    return FindUserByIdResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindUserByIdResponse>, I>>(object: I): FindUserByIdResponse {
    const message = createBaseFindUserByIdResponse();
    message.userData = (object.userData !== undefined && object.userData !== null)
      ? UserDataId.fromPartial(object.userData)
      : undefined;
    message.notFound = (object.notFound !== undefined && object.notFound !== null)
      ? UserNotFoundResponse.fromPartial(object.notFound)
      : undefined;
    return message;
  },
};

function createBaseUserDataId(): UserDataId {
  return { userId: 0, phoneNumber: "", email: "", passwordHash: "", username: "", chatReferences: [] };
}

export const UserDataId: MessageFns<UserDataId> = {
  encode(message: UserDataId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(18).string(message.phoneNumber);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    if (message.passwordHash !== "") {
      writer.uint32(34).string(message.passwordHash);
    }
    if (message.username !== "") {
      writer.uint32(42).string(message.username);
    }
    for (const v of message.chatReferences) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserDataId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserDataId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.passwordHash = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.chatReferences.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserDataId {
    return {
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      passwordHash: isSet(object.passwordHash) ? globalThis.String(object.passwordHash) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      chatReferences: globalThis.Array.isArray(object?.chatReferences)
        ? object.chatReferences.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: UserDataId): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.passwordHash !== "") {
      obj.passwordHash = message.passwordHash;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.chatReferences?.length) {
      obj.chatReferences = message.chatReferences;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserDataId>, I>>(base?: I): UserDataId {
    return UserDataId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserDataId>, I>>(object: I): UserDataId {
    const message = createBaseUserDataId();
    message.userId = object.userId ?? 0;
    message.phoneNumber = object.phoneNumber ?? "";
    message.email = object.email ?? "";
    message.passwordHash = object.passwordHash ?? "";
    message.username = object.username ?? "";
    message.chatReferences = object.chatReferences?.map((e) => e) || [];
    return message;
  },
};

function createBaseFindUserByUsernameRequest(): FindUserByUsernameRequest {
  return { username: "" };
}

export const FindUserByUsernameRequest: MessageFns<FindUserByUsernameRequest> = {
  encode(message: FindUserByUsernameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByUsernameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByUsernameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindUserByUsernameRequest {
    return { username: isSet(object.username) ? globalThis.String(object.username) : "" };
  },

  toJSON(message: FindUserByUsernameRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindUserByUsernameRequest>, I>>(base?: I): FindUserByUsernameRequest {
    return FindUserByUsernameRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindUserByUsernameRequest>, I>>(object: I): FindUserByUsernameRequest {
    const message = createBaseFindUserByUsernameRequest();
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseFindUserByUsernameResponse(): FindUserByUsernameResponse {
  return { users: [] };
}

export const FindUserByUsernameResponse: MessageFns<FindUserByUsernameResponse> = {
  encode(message: FindUserByUsernameResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.users) {
      UserArray.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByUsernameResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByUsernameResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.users.push(UserArray.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindUserByUsernameResponse {
    return {
      users: globalThis.Array.isArray(object?.users) ? object.users.map((e: any) => UserArray.fromJSON(e)) : [],
    };
  },

  toJSON(message: FindUserByUsernameResponse): unknown {
    const obj: any = {};
    if (message.users?.length) {
      obj.users = message.users.map((e) => UserArray.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindUserByUsernameResponse>, I>>(base?: I): FindUserByUsernameResponse {
    return FindUserByUsernameResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindUserByUsernameResponse>, I>>(object: I): FindUserByUsernameResponse {
    const message = createBaseFindUserByUsernameResponse();
    message.users = object.users?.map((e) => UserArray.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFindUserByEmailRequest(): FindUserByEmailRequest {
  return { email: "" };
}

export const FindUserByEmailRequest: MessageFns<FindUserByEmailRequest> = {
  encode(message: FindUserByEmailRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByEmailRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByEmailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindUserByEmailRequest {
    return { email: isSet(object.email) ? globalThis.String(object.email) : "" };
  },

  toJSON(message: FindUserByEmailRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindUserByEmailRequest>, I>>(base?: I): FindUserByEmailRequest {
    return FindUserByEmailRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindUserByEmailRequest>, I>>(object: I): FindUserByEmailRequest {
    const message = createBaseFindUserByEmailRequest();
    message.email = object.email ?? "";
    return message;
  },
};

function createBaseFindUserByEmailResponse(): FindUserByEmailResponse {
  return { userData: undefined, notFound: undefined };
}

export const FindUserByEmailResponse: MessageFns<FindUserByEmailResponse> = {
  encode(message: FindUserByEmailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userData !== undefined) {
      UserData.encode(message.userData, writer.uint32(10).fork()).join();
    }
    if (message.notFound !== undefined) {
      UserNotFoundResponse.encode(message.notFound, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByEmailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByEmailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userData = UserData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.notFound = UserNotFoundResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindUserByEmailResponse {
    return {
      userData: isSet(object.userData) ? UserData.fromJSON(object.userData) : undefined,
      notFound: isSet(object.notFound) ? UserNotFoundResponse.fromJSON(object.notFound) : undefined,
    };
  },

  toJSON(message: FindUserByEmailResponse): unknown {
    const obj: any = {};
    if (message.userData !== undefined) {
      obj.userData = UserData.toJSON(message.userData);
    }
    if (message.notFound !== undefined) {
      obj.notFound = UserNotFoundResponse.toJSON(message.notFound);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindUserByEmailResponse>, I>>(base?: I): FindUserByEmailResponse {
    return FindUserByEmailResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindUserByEmailResponse>, I>>(object: I): FindUserByEmailResponse {
    const message = createBaseFindUserByEmailResponse();
    message.userData = (object.userData !== undefined && object.userData !== null)
      ? UserData.fromPartial(object.userData)
      : undefined;
    message.notFound = (object.notFound !== undefined && object.notFound !== null)
      ? UserNotFoundResponse.fromPartial(object.notFound)
      : undefined;
    return message;
  },
};

function createBaseFindUserByPhoneNumberRequest(): FindUserByPhoneNumberRequest {
  return { phoneNumber: "" };
}

export const FindUserByPhoneNumberRequest: MessageFns<FindUserByPhoneNumberRequest> = {
  encode(message: FindUserByPhoneNumberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.phoneNumber !== "") {
      writer.uint32(10).string(message.phoneNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByPhoneNumberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByPhoneNumberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindUserByPhoneNumberRequest {
    return { phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "" };
  },

  toJSON(message: FindUserByPhoneNumberRequest): unknown {
    const obj: any = {};
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindUserByPhoneNumberRequest>, I>>(base?: I): FindUserByPhoneNumberRequest {
    return FindUserByPhoneNumberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindUserByPhoneNumberRequest>, I>>(object: I): FindUserByPhoneNumberRequest {
    const message = createBaseFindUserByPhoneNumberRequest();
    message.phoneNumber = object.phoneNumber ?? "";
    return message;
  },
};

function createBaseFindUserByPhoneNumberResponse(): FindUserByPhoneNumberResponse {
  return { userData: undefined, notFound: undefined };
}

export const FindUserByPhoneNumberResponse: MessageFns<FindUserByPhoneNumberResponse> = {
  encode(message: FindUserByPhoneNumberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userData !== undefined) {
      UserData.encode(message.userData, writer.uint32(10).fork()).join();
    }
    if (message.notFound !== undefined) {
      UserNotFoundResponse.encode(message.notFound, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByPhoneNumberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByPhoneNumberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userData = UserData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.notFound = UserNotFoundResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindUserByPhoneNumberResponse {
    return {
      userData: isSet(object.userData) ? UserData.fromJSON(object.userData) : undefined,
      notFound: isSet(object.notFound) ? UserNotFoundResponse.fromJSON(object.notFound) : undefined,
    };
  },

  toJSON(message: FindUserByPhoneNumberResponse): unknown {
    const obj: any = {};
    if (message.userData !== undefined) {
      obj.userData = UserData.toJSON(message.userData);
    }
    if (message.notFound !== undefined) {
      obj.notFound = UserNotFoundResponse.toJSON(message.notFound);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindUserByPhoneNumberResponse>, I>>(base?: I): FindUserByPhoneNumberResponse {
    return FindUserByPhoneNumberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindUserByPhoneNumberResponse>, I>>(
    object: I,
  ): FindUserByPhoneNumberResponse {
    const message = createBaseFindUserByPhoneNumberResponse();
    message.userData = (object.userData !== undefined && object.userData !== null)
      ? UserData.fromPartial(object.userData)
      : undefined;
    message.notFound = (object.notFound !== undefined && object.notFound !== null)
      ? UserNotFoundResponse.fromPartial(object.notFound)
      : undefined;
    return message;
  },
};

function createBaseUserData(): UserData {
  return { userId: 0, phoneNumber: "", email: "", passwordHash: "", username: "" };
}

export const UserData: MessageFns<UserData> = {
  encode(message: UserData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(18).string(message.phoneNumber);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    if (message.passwordHash !== "") {
      writer.uint32(34).string(message.passwordHash);
    }
    if (message.username !== "") {
      writer.uint32(42).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.passwordHash = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserData {
    return {
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      passwordHash: isSet(object.passwordHash) ? globalThis.String(object.passwordHash) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
    };
  },

  toJSON(message: UserData): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.passwordHash !== "") {
      obj.passwordHash = message.passwordHash;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserData>, I>>(base?: I): UserData {
    return UserData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserData>, I>>(object: I): UserData {
    const message = createBaseUserData();
    message.userId = object.userId ?? 0;
    message.phoneNumber = object.phoneNumber ?? "";
    message.email = object.email ?? "";
    message.passwordHash = object.passwordHash ?? "";
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseUserNotFoundResponse(): UserNotFoundResponse {
  return { message: "", status: 0 };
}

export const UserNotFoundResponse: MessageFns<UserNotFoundResponse> = {
  encode(message: UserNotFoundResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserNotFoundResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserNotFoundResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserNotFoundResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
    };
  },

  toJSON(message: UserNotFoundResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserNotFoundResponse>, I>>(base?: I): UserNotFoundResponse {
    return UserNotFoundResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserNotFoundResponse>, I>>(object: I): UserNotFoundResponse {
    const message = createBaseUserNotFoundResponse();
    message.message = object.message ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseResponseMessage(): ResponseMessage {
  return { message: "", status: 0 };
}

export const ResponseMessage: MessageFns<ResponseMessage> = {
  encode(message: ResponseMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResponseMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResponseMessage {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
    };
  },

  toJSON(message: ResponseMessage): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResponseMessage>, I>>(base?: I): ResponseMessage {
    return ResponseMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResponseMessage>, I>>(object: I): ResponseMessage {
    const message = createBaseResponseMessage();
    message.message = object.message ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseUserArray(): UserArray {
  return { userId: 0, username: "" };
}

export const UserArray: MessageFns<UserArray> = {
  encode(message: UserArray, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserArray {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserArray();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserArray {
    return {
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
    };
  },

  toJSON(message: UserArray): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserArray>, I>>(base?: I): UserArray {
    return UserArray.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserArray>, I>>(object: I): UserArray {
    const message = createBaseUserArray();
    message.userId = object.userId ?? 0;
    message.username = object.username ?? "";
    return message;
  },
};

export interface UserService {
  CreateNewUser(request: CreateNewUserRequest): Promise<CreateNewUserResponse>;
  FindUserById(request: FindUserByIdRequest): Promise<FindUserByIdResponse>;
  FindUserByUsername(request: FindUserByUsernameRequest): Promise<FindUserByUsernameResponse>;
  FindUserByEmail(request: FindUserByEmailRequest): Promise<FindUserByEmailResponse>;
  FindUserByPhoneNumber(request: FindUserByPhoneNumberRequest): Promise<FindUserByPhoneNumberResponse>;
  AddChatToUser(request: AddChatToUserRequest): Promise<AddChatToUserResponse>;
  RemoveChatFromUser(request: RemoveChatFromUserRequest): Promise<RemoveChatFromUserResponse>;
  RemoveArrayChat(request: RemoveArrayChatRequest): Promise<RemoveArrayChatResponse>;
  RemoveAccount(request: RemoveAccountRequest): Promise<RemoveAccountResponse>;
  GetPasswordUser(request: GetPasswordUserRequest): Promise<GetPasswordUserResponse>;
  GetUserProfile(request: GetUserProfileRequest): Promise<GetUserProfileResponse>;
  UpdateUserProfile(request: UpdateUserProfileRequest): Promise<UpdateUserProfileResponse>;
  UpdateUserPassword(request: UpdateUserPasswordRequest): Promise<UpdateUserPasswordResponse>;
  ToggleUserProfileCheck(request: ToggleUserProfileCheckRequset): Promise<ToggleUserProfileCheckResponse>;
}

export const UserServiceServiceName = "user.UserService";
export class UserServiceClientImpl implements UserService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || UserServiceServiceName;
    this.rpc = rpc;
    this.CreateNewUser = this.CreateNewUser.bind(this);
    this.FindUserById = this.FindUserById.bind(this);
    this.FindUserByUsername = this.FindUserByUsername.bind(this);
    this.FindUserByEmail = this.FindUserByEmail.bind(this);
    this.FindUserByPhoneNumber = this.FindUserByPhoneNumber.bind(this);
    this.AddChatToUser = this.AddChatToUser.bind(this);
    this.RemoveChatFromUser = this.RemoveChatFromUser.bind(this);
    this.RemoveArrayChat = this.RemoveArrayChat.bind(this);
    this.RemoveAccount = this.RemoveAccount.bind(this);
    this.GetPasswordUser = this.GetPasswordUser.bind(this);
    this.GetUserProfile = this.GetUserProfile.bind(this);
    this.UpdateUserProfile = this.UpdateUserProfile.bind(this);
    this.UpdateUserPassword = this.UpdateUserPassword.bind(this);
    this.ToggleUserProfileCheck = this.ToggleUserProfileCheck.bind(this);
  }
  CreateNewUser(request: CreateNewUserRequest): Promise<CreateNewUserResponse> {
    const data = CreateNewUserRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateNewUser", data);
    return promise.then((data) => CreateNewUserResponse.decode(new BinaryReader(data)));
  }

  FindUserById(request: FindUserByIdRequest): Promise<FindUserByIdResponse> {
    const data = FindUserByIdRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FindUserById", data);
    return promise.then((data) => FindUserByIdResponse.decode(new BinaryReader(data)));
  }

  FindUserByUsername(request: FindUserByUsernameRequest): Promise<FindUserByUsernameResponse> {
    const data = FindUserByUsernameRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FindUserByUsername", data);
    return promise.then((data) => FindUserByUsernameResponse.decode(new BinaryReader(data)));
  }

  FindUserByEmail(request: FindUserByEmailRequest): Promise<FindUserByEmailResponse> {
    const data = FindUserByEmailRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FindUserByEmail", data);
    return promise.then((data) => FindUserByEmailResponse.decode(new BinaryReader(data)));
  }

  FindUserByPhoneNumber(request: FindUserByPhoneNumberRequest): Promise<FindUserByPhoneNumberResponse> {
    const data = FindUserByPhoneNumberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FindUserByPhoneNumber", data);
    return promise.then((data) => FindUserByPhoneNumberResponse.decode(new BinaryReader(data)));
  }

  AddChatToUser(request: AddChatToUserRequest): Promise<AddChatToUserResponse> {
    const data = AddChatToUserRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "AddChatToUser", data);
    return promise.then((data) => AddChatToUserResponse.decode(new BinaryReader(data)));
  }

  RemoveChatFromUser(request: RemoveChatFromUserRequest): Promise<RemoveChatFromUserResponse> {
    const data = RemoveChatFromUserRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RemoveChatFromUser", data);
    return promise.then((data) => RemoveChatFromUserResponse.decode(new BinaryReader(data)));
  }

  RemoveArrayChat(request: RemoveArrayChatRequest): Promise<RemoveArrayChatResponse> {
    const data = RemoveArrayChatRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RemoveArrayChat", data);
    return promise.then((data) => RemoveArrayChatResponse.decode(new BinaryReader(data)));
  }

  RemoveAccount(request: RemoveAccountRequest): Promise<RemoveAccountResponse> {
    const data = RemoveAccountRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RemoveAccount", data);
    return promise.then((data) => RemoveAccountResponse.decode(new BinaryReader(data)));
  }

  GetPasswordUser(request: GetPasswordUserRequest): Promise<GetPasswordUserResponse> {
    const data = GetPasswordUserRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetPasswordUser", data);
    return promise.then((data) => GetPasswordUserResponse.decode(new BinaryReader(data)));
  }

  GetUserProfile(request: GetUserProfileRequest): Promise<GetUserProfileResponse> {
    const data = GetUserProfileRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetUserProfile", data);
    return promise.then((data) => GetUserProfileResponse.decode(new BinaryReader(data)));
  }

  UpdateUserProfile(request: UpdateUserProfileRequest): Promise<UpdateUserProfileResponse> {
    const data = UpdateUserProfileRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateUserProfile", data);
    return promise.then((data) => UpdateUserProfileResponse.decode(new BinaryReader(data)));
  }

  UpdateUserPassword(request: UpdateUserPasswordRequest): Promise<UpdateUserPasswordResponse> {
    const data = UpdateUserPasswordRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateUserPassword", data);
    return promise.then((data) => UpdateUserPasswordResponse.decode(new BinaryReader(data)));
  }

  ToggleUserProfileCheck(request: ToggleUserProfileCheckRequset): Promise<ToggleUserProfileCheckResponse> {
    const data = ToggleUserProfileCheckRequset.encode(request).finish();
    const promise = this.rpc.request(this.service, "ToggleUserProfileCheck", data);
    return promise.then((data) => ToggleUserProfileCheckResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
