services:
  user_microservice:
    container_name: user_microserice
    build:
      context: ../user_microservice
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    restart: always
    networks:
      - telegramm_network
    depends_on:
      - mysql_server
    env_file: ../user_microservice/.env
    environment:
      DATABASE_URL: mysql://admin:admin@mysql_server:3306/telegramm

  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    env_file:
      - ../config/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql_data:/var/lib/mysql
    networks:
      - telegramm_network

networks:
  telegramm_network:
    driver: bridge

volumes:
  mysql_data: