global:
  scrape_interval: 15s  # интервал сбора метрик

scrape_configs:
  - job_name: 'telegramm'  # имя задания для вашего приложения
    static_configs:
      - targets: ['localhost:50051', 'localhost:50052', 'localhost:50053', 'localhost:5050']
